export enum HomePageLocators {
    homeButton = ".fa fa-home",
    productsButton = "a[href='/products']",
    cartButton = "a[href='/view_cart']:contains('Cart')",
    signup_loginButton = "a[href='/login']",
    testcasesButton = "a[href='/test_cases']:contains[' Test Cases']",  
    apitestingButon = "a[href='/api_list']:conatins[' API Testing']",
    videotutorialsButton = ".fa.fa-youtube-play",
    contactUsButton = "a[href='/contact_us']",
    logo = "img[alt*='Website for automation practice']",
    sliderleftArrow = "a[class='left control-carousel hidden-xs']",
    sliderrightArrow = "a[class='right control-carousel hidden-xs']",
    leftSidebar = '.left-sidebar',
    featuresitemsHeader = ".features_items",
    featureitemsTable = "div.col-sm-4:not([css='1'])",
    recommendeditemsHeader = ".recommended_items",
    recommendedleftArrow = ".left.recommended-item-control",
    recommendedrightArrow = ".right.recommended-item-control",
    subscribitionText = "//h2[.='Subscription']",
    subscribeEmail = "#susbscribe_email",
    subscribeButton = "#subscribe",
    scrollupButton = "#scrollUp"
}   

export enum LoginPageLocators {
    loginText = "//h2[.='Login to your account']",
    loginEmail ="input[data-qa='login-email']",
    loginPassword = "input[data-qa='login-password']",
    loginButton = "button[data-qa='login-button']",
    orText = ".or",
    signupText = "//h2[.='New User Signup!']",
    signupName = "input[data-qa='signup-name']",
    signupEmail = "input[data-qa='signup-email']",
    signupButton = "button[data-qa='signup-button']",
    logoutButton = "a[href='/logout']",
    loginCredentialsToaster = "p[style='color: red;']",
    loggedInText = "a:has(i.fa-user)",
}

export enum ProuctsPageLocators {
    searchBox = "#search_product",
    searchButton = "#submit_search",
    productsCategory = "div[class*='panel-group category-products']",
    womenCategory = "a[href='#Women']",
    menCategory = "a[href='#Men']",
    kidsCategory = "a[href='#Kids']",
    brandsCategory = ".brands_products",
    brandPolo = "a[href*='/brand_products/Polo']",
    brandHM = "a[href*='/brand_products/H&M']",
    brandMadame = "a[href*='/brand_products/Madame']",
    brandMastHarbour = "a[href='/brand_products/Mast & Harbour']",
    brandBabyhug = "a[href='/brand_products/Babyhug']",
    brandAllenSolly = "a[href='/brand_products/Allen Solly Junior']",
    brandKooiekids = "a[href='/brand_products/Kookie Kids']",
    brandBiba = "a[href='/brand_products/Biba']",
    productscrollupButton = "#scrollUp", 
    viewProduct1 = "a[href='/product_details/1']",
    addtoCart1 = "data-product-id='2'",
    continueShoppingButton = "button[data-dismiss='modal']",
    viewitemAddedToCart = "a[href='/view_cart'][css='2']",
    productName = ".product-information h2",
    productDetails = ".product-information p",
    productPrice = ".product-information span span",
    cartButtononPP = ".btn.btn-default.cart",
    productCounter = "#quantity",
    newArrival = "newarrival",
}

export enum SignupPageLocators {
    mrradioButton = "label[for='id_gender1']",
    mrsradioButton = "label[for='id_gender2']",
    name = "input[data-qa='name']",
    email = "input[data-qa='email']",
    password = "input[data-qa='password']",
    day = "select[data-qa='days']",
    month = "select[data-qa='months']",
    year = "select[data-qa='years']",
    newsletterCheckbox = "#newsletter",
    specialoffersCheckbox = "#optin",
    firstName = "input[data-qa='first_name']",
    lastName = "input[data-qa='last_name']",
    company = "input[data-qa='company']",
    address1 = "input[data-qa='address']",
    address2 = "input[data-qa='address2']",
    country = "select[data-qa='country']",
    state = "input[data-qa='state']",
    city = "input[data-qa='city']",
    zipcode = "input[data-qa='zipcode']",
    mobileNumber = "input[data-qa='mobile_number']",
    createAccountButton = "button[data-qa='create-account']",
    accountCreatedText = "h2[data-qa='account-created']",
    continueButton = "a[data-qa='continue-button']",
    accountDeletedText = "h2[data-qa='account-deleted']",
    deleteAccountButton = "a[href='/delete_account']",
    emailExistsText = "p[style='color: red;']",
}
